In [4]:
import pandas as pd 
import numpy as np
from pandas_datareader import data as pdr

import yfinance as yf #yahoo finance stock data
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from math import sqrt

import tensorflow as tf
from tensorflow import keras

from statsmodels.tsa.stattools import adfuller

from sklearn.linear_model import LinearRegression,ElasticNet
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

from keras.models import Sequential
from keras.layers import Activation,Conv2D,MaxPooling2D,Flatten,Dropout,Dense,LSTM,BatchNormalization

stock="GOOG"
period=14

In [5]:
end=datetime.datetime(2019,6,15,0,0,0)

In [6]:
min=yf.download(tickers=stock,period="3d",enddate=end,interval="1m")
thirt_min=yf.download(tickers=stock,period="60d",enddate=end, interval="30m")
hour=yf.download(tickers=stock,period="150d",enddate=end,interval="1h")
daily=yf.download(tickers=stock,period="1000d",enddate=end,interval="1d")
weekly=yf.download(tickers=stock,period="3800d",enddate=end,interval="1wk")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [51]:
def Prepare_dataset(df):
    from sklearn.model_selection import train_test_split

    df.dropna(inplace=True,how="all",axis=0)
    df.fillna(inplace=True,method="ffill")
    df=df.iloc[-755:]
    y=df.shift(-1).iloc[:-1,3].values
    X=df.drop(["Adj Close","Close"],1)
    X=X.iloc[:-1,:]
    return train_test_split(X, y, test_size=0.2, random_state=0,shuffle=False)

def Rmse(y,y_pred):
    return np.sqrt(((y_pred - y) ** 2).mean())

def Arima_build(ts_train,ts_test):
  def arimamodel(timeseriesarray):
    import pmdarima as pmd
    autoarima_model = pmd.auto_arima(timeseriesarray, 
                              start_p=1,
                              max_p=5,
                              start_q=1,
                              max_q=5,
                              test="adf",
                              max_order=5,
                              seasonal_test="OCSB",
                              stepwise=False,
                              n_jobs=-1,
                              trace=True)
    return autoarima_model

  arima_model = arimamodel(ts_train)
  preds=arima_model.predict(len(ts_test))
  return ts_test

def plot_history(history):
    hist=pd.DataFrame(history.history)
    hist["epoch"]=history.epoch

    plt.figure()
    plt.xlabel("Epoch")
    plt.ylabel("Mean Abs Error")
    plt.plot(hist.epoch,hist.mae,label="Train error")
    plt.plot(hist.epoch,hist.val_mae,label="Val error")
    plt.legend()
    plt.ylim([0,hist.mae.max()])

def Build_lstm(X_train,X_test,y_train,scale=True):
    if scale==True:     
        x_scaler = StandardScaler()
        X_train=x_scaler.fit_transform(X_train)
        X_test=x_scaler.transform(X_test)
        
    x_train=np.array(X_train).reshape(X_train.shape[0],X_train.shape[1],1)
    x_test=np.array(X_test).reshape(X_test.shape[0],X_test.shape[1],1)

    model = Sequential()
    model.add(LSTM(50, return_sequences=True))
    model.add(BatchNormalization())
    model.add(LSTM(units=100))
    model.add(Dense(units=25))
    model.add(Dense(units=1))

    model.compile(loss="mse",optimizer="nadam",metrics=['accuracy'])
    model.fit(x_train, np.array(y_train), epochs=500,verbose=0)
    preds=model.predict(x_test, batch_size=1)

    return preds



In [8]:
datasets={}
datasets["1m"]=Prepare_dataset(min)
datasets["30m"]=Prepare_dataset(thirt_min)
datasets["1h"]=Prepare_dataset(hour)
datasets["D"]=Prepare_dataset(daily)
datasets["W"]=Prepare_dataset(weekly)

In [57]:
result=pd.DataFrame(columns=["1m","30m","1h","D","W"])

for key in datasets:
    X_train=datasets[key][0]
    X_test=datasets[key][1]
    y_train=datasets[key][2]
    y_test=datasets[key][3]

    elastic=ElasticNet().fit(X_train, y_train)
    elastic_preds=elastic.predict(X_test)
    result.loc["Elastic net",key]=[Rmse(y_test,elastic_preds)]

    rf=RandomForestRegressor(n_estimators=100,max_depth=12,random_state=0).fit(X_train, y_train)
    rf_preds=rf.predict(X_test)
    result.loc["Random forest",key]=[Rmse(y_test,rf_preds)]

    arima_preds=Arima_build(datasets[key][0]["Open"],datasets[key][1]["Open"])
    result.loc["ARIMA",key]=[Rmse(y_test,arima_preds)]

    lstm_preds=Build_lstm(X_train,X_test,y_train,scale=False)
    result.loc["LSTM",key]=[Rmse(y_test,lstm_preds)]

    lstm_preds=Build_lstm(X_train,X_test,y_train)
    
    result.loc["LSTM scaled",key]=[Rmse(y_test,lstm_preds)]

    print(f"Model for {key} dataset is done")
result

Total fit time: 5.513 seconds
Model for 1m dataset is done
Total fit time: 2.236 seconds
Model for 30m dataset is done
Total fit time: 2.094 seconds
Model for 1h dataset is done
Total fit time: 2.330 seconds
Model for D dataset is done
Total fit time: 2.422 seconds
Model for W dataset is done


1m                   30m  \
Elastic net     [0.777264013508635]   [6.491790425405427]   
Random forest  [2.9410001649633064]  [10.538567466761608]   
ARIMA          [0.9013635156414669]   [7.871950982744445]   
LSTM           [27.356444605924537]  [207.47638083812248]   
LSTM scaled     [27.36894235322352]  [49.690797957413814]   

                                 1h                     D  \
Elastic net    [16.202775669932727]  [29.626953499136818]   
Random forest  [51.399691553311904]  [106.07085747935972]   
ARIMA          [18.178468278333302]   [36.06349620425008]   
LSTM           [204.23968027985612]   [361.6701485887411]   
LSTM scaled    [125.04143949809173]  [164.72258322381444]   

                                  W  
Elastic net     [50.52223733807723]  
Random forest  [252.14523610667646]  
ARIMA           [60.69536207607332]  
LSTM            [323.0741169211304]  
LSTM scaled    [310.35409978054753]

In [53]:
preds=Build_lstm(datasets["1m"][0],datasets["1m"][1],datasets["1m"][2],scale=False)

In [54]:
preds[:2],datasets["1m"][3][:2]

(array([[1738.363],
        [1738.363]], dtype=float32),
 array([1763.65002441, 1763.29504395]))

In [56]:
preds[:2],datasets["1m"][3][:2]

(array([[1738.363],
        [1738.363]], dtype=float32),
 array([1763.65002441, 1763.29504395]))